### ISSUE TITLE
polymer outputs in modded custom puzzles are not saved correctly

### ISSUE THREAD

**Issue by icwass** [QuintessentialOM/Quintessential#8]
Consider the following polymer, where we use the Quintessential AtomType names for the atoms:
`(earth) - (repeat)`

Vanilla custom puzzles save this output correctly.

Modded custom puzzles will first expand the molecule into its Sim form, _then_ save it:
`(earth) - (earth) - (earth) - (earth) - (earth) - (earth) - ()`
where the last atom is saved with an empty string for its AtomType.

**Comment by l-Luna** [comment]
Fixed in 0.5.0.
