### ISSUE TITLE
polymer outputs in modded puzzle files are not loaded correctly

### ISSUE THREAD

**Issue by icwass** [QuintessentialOM/Quintessential#9]
When loading vanilla puzzle files, the game will process the inputs and outputs. If it comes across an output that contains the repeat atom, it will expand the molecule into its Sim form, where:
- the repeat atom is removed
- the monomer is expanded into 6 copies to form the polymer
- a no-name atom (with byte ID 0 and the same graphics as the repeat atom) is added to the end of the molecule

When modded puzzle files are loaded, outputs with a repeat atom seem to be left unprocessed. They act like standard outputs in the Sim, but will crash the game if an atom is placed above one of its hexes:
```
(8/16/2023 11:13:55 PM) System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Sim.method_1846(HexIndex param_5385, Molecule param_5386, Molecule param_5387)
   at Sim.method_1832(Boolean param_5369)
   at Sim.method_1827()
   ...
```

Attached is an example puzzle file that causes the problem.
[polymer-test.puzzle.zip](https://github.com/QuintessentialOM/Quintessential/files/12365432/polymer-test.puzzle.zip)

**Comment by l-Luna** [comment]
Fixed in 0.5.0.
